packages:
  - apps/*
  - packages/*

allowBuilds:
  esbuild: true
  workerd: true
  sharp: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - miniflare@5.20260926.0-alpha
  - wrangler@4.142.0
  - '@cloudflare/vitest-plugin@1.3.0'
